config/routes.rb
Rails.application.routes.draw do
  get 'product_claims/hide'
  resources :product_claims
  devise_for :users, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'product_claims#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product_claim.rb
class ProductClaim < ApplicationRecord
  belongs_to :user, :foreign_key => "user_id"
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = "product_claims_users"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable
  has_many :product_claims
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/product_claims_controller.rb
class ProductClaimsController < ApplicationController
  before_action :set_product_claim, only: [:show, :edit, :update, :destroy]
  before_action :set_dropdowns, only: [:new, :edit]
  before_action :set_header, only: [:new, :edit, :index, :show]

  # GET /product_claims
  def index
    @product_claims = ProductClaim.all
  end

  # GET /product_claims/1
  def show
  end

  # GET /product_claims/new
  def new
    @product_claim = ProductClaim.new
  end

  # GET /product_claims/1/edit
  def edit
  end

  # POST /product_claims
  def create
    @product_claim = ProductClaim.new(product_claim_params)
    @product_claim.user_id = current_user.id

    respond_to do |format|
      if @product_claim.save
        format.html { redirect_to @product_claim, notice: 'Product claim was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /product_claims/1
  def update
    respond_to do |format|
      if @product_claim.update(product_claim_params)
        format.html { redirect_to @product_claim, notice: 'Product claim was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /product_claims/1
  def destroy
    @product_claim.destroy
    respond_to do |format|
      format.html { redirect_to product_claims_url, notice: 'Product claim was successfully destroyed.' }
    end
  end

  def hide
    @show_header = false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_claim
      @product_claim = ProductClaim.find(params[:id])
    end

    def set_dropdowns
      @supermarket = ['BALDUCHI', 'ACME', 'STOPNSHOP']
      @category = ['CHICKEN', 'BEEF', 'PORK']
    end

    def set_header
      @show_header = true
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_claim_params
      params.require(:product_claim).permit(:user_id, :supermarket, :category, :brand, :description, :abf, :organic, :grassfed, :never, :humane, :promo, :expiration_date, :image, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_date(date)
    if date
      formatted = date.strftime("%e %b %Y")
    else
      formatted = ' '
    end
    formatted
  end
  def human_boolean(boolean)
      boolean ? 'Yes' : 'No'
  end
end

app/helpers/product_claims_helper.rb
module ProductClaimsHelper
end

app/views/layouts/_header.html.erb
<nav class="">
    <ul>
        <span id="navbar">
            <span><%= link_to 'New', new_product_claim_path %></span>
            <span><%= link_to "List", product_claims_path %></span>
            <span><%= link_to "Hide", product_claims_hide_path %></span>
        </span>
    </ul>
</nav>
<br>
<h2 class="title">Product Claims
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductClaims</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @show_header %>
      <div style="position: fixed; top: 0px; width: 100%; height: 8em; background-color: white; z-index: 100;">
        <%= render 'layouts/header' %>
      </div>
      <div style="margin-top: 8.5em;">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script src="/assets/printPreview.js"></script>
    <script src="/assets/myjavascript.js"></script>
  </body>
</html>

app/views/product_claims/_form.html.erb
<%= form_with(model: product_claim, local: true, html: { multipart: true }) do |form| %>
  <% if product_claim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_claim.errors.count, "error") %> prohibited this product_claim from being saved:</h2>

      <ul>
      <% product_claim.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <thead>
      <tr>
        <th> <%= form.label :supermarket %> </th>
        <th> <%= form.label :category %> </th>
        <th> <%= form.label :brand %> </th>
        <th> <%= form.label :description %> </th>
        <th> <%= form.label :expiration_date %> </th>
        <th> <%= form.label :price, 'Price per Lb' %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.select :supermarket, @supermarket, {}, {:value => params[:supermarket], id: :product_claim_supermarket} %> </td>
        <td> <%= form.select :category, @category, {}, {:value => params[:category], id: :product_claim_category} %> </td>
        <td> <%= form.text_field :brand, size: 10, id: :product_claim_brand %> </td>
        <td> <%= form.text_field :description, id: :product_claim_description %> </td>
        <td> <%= form.date_field :expiration_date, id: :product_claim_expiration_date %> </td>
        <td> <%= form.number_field :price, id: :product_claim_price, :step => 0.01 %> </td>
      </tr>
    </tbody>
  </table>
  <table>
    <thead>
      <tr>
        <th> <%= form.label :abf, 'ABF' %> </th>
        <th> <%= form.label :organic %> </th>
        <th> <%= form.label :grassfed, 'Free range' %> </th>
        <th> <%= form.label :never %> </th>
        <th> <%= form.label :humane %> </th>
        <th> <%= form.label :promo %> </th>
        <th> <%= form.label :image %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :abf, id: :product_claim_abf %> </td>
        <td> <%= form.check_box :organic, id: :product_claim_organic %> </td>
        <td> <%= form.check_box :grassfed, id: :product_claim_grassfed %> </td>
        <td> <%= form.check_box :never, id: :product_claim_never %> </td>
        <td> <%= form.check_box :humane, id: :product_claim_humane %> </td>
        <td> <%= form.check_box :promo, id: :product_claim_promo %> </td>
        <td> <%= form.file_field :image, id: :product_claim_image %> </td>
      </tr>
    </tbody>
  </table>

  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_claims/edit.html.erb
<%= render 'form', product_claim: @product_claim %>

app/views/product_claims/hide.html.erb
<%= image_tag("Shopping_list.jpg") %>

app/views/product_claims/index.html.erb
<p id="notice"><%= notice %></p>

<table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th>Supermarket</th>
      <th>Category</th>
      <th>Brand</th>
      <th>Description</th>
      <th>Promo</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @product_claims.each do |product_claim| %>
      <tr>
        <td><%= product_claim.supermarket %></td>
        <td><%= product_claim.category %></td>
        <td><%= product_claim.brand %></td>
        <td><%= product_claim.description %></td>
        <td> <%= human_boolean(product_claim.promo) %> </td>
        <td><%= link_to 'Show', product_claim %></td>
        <td><%= link_to 'Edit', edit_product_claim_path(product_claim) %></td>
        <td><%= link_to 'Delete', product_claim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/product_claims/new.html.erb
<%= render 'form', product_claim: @product_claim %>

app/views/product_claims/show.html.erb
<p id="notice"><%= notice %></p>

    <strong>Supermarket:</strong>
    <%= @product_claim.supermarket %>&emsp;
    <strong>Category:</strong>
    <%= @product_claim.category %>&emsp;
    <strong>Brand:</strong>
    <%= @product_claim.brand %>&emsp;
    <strong>Description:</strong>
    <%= @product_claim.description %>&emsp;
    <strong>Expiration date:</strong>
    <%= display_date(@product_claim.expiration_date) %>&emsp;
    <strong>Price per Lb:</strong>
    <%= @product_claim.price %>
    <br>
    <strong>ABF?:</strong>
    <%= human_boolean( @product_claim.abf) %>&emsp;
    <strong>Organic?:</strong>
    <%= human_boolean( @product_claim.organic) %>&emsp;
    <strong>Free range?:</strong>
    <%= human_boolean( @product_claim.grassfed) %>&emsp;
    <strong>Never ever?:</strong>
    <%= human_boolean( @product_claim.never) %>&emsp;
    <strong>Humane?:</strong>
    <%= human_boolean( @product_claim.humane) %>&emsp;
    <strong>Promotion?:</strong>
    <%= human_boolean( @product_claim.promo) %>&emsp;
    <strong>Image:</strong>
    <% if @product_claim.image.url %>
      <%= image_tag(@product_claim.image.url, size: "300x200") %>
    <% end %>

</p>